import { q, type TriviaQuestion } from './types'

/** Hand-written core scenarios (token rules verified). */
export const CORE_TRIVIA_QUESTIONS: TriviaQuestion[] = [
  q(
    'stack-bolt-giant',
    'You cast Lightning Bolt targeting a 5/5 creature. In response, your opponent casts Giant Growth on it (+3/+3). The stack resolves top-down. What happens?',
    [
      'Lightning Bolt fizzles because the target changed',
      'Giant Growth resolves first; the creature becomes 5/8 and survives the 3 damage',
      'Lightning Bolt resolves first; the creature dies before the pump',
      'Both spells are countered',
    ],
    1,
    'Giant Growth was cast in response, so it is on top of the stack. It resolves first, then Lightning Bolt deals 3 damage to a 5/8 creature.',
  ),
  q(
    'sba-lethal',
    'A 2/2 creature is dealt 2 damage. No player passes priority. What happens next?',
    [
      'Nothing until a player takes an action',
      'The creature stays on the battlefield with 2 damage marked',
      'State-based actions destroy the creature for having lethal damage',
      'The damage is removed at end of turn automatically',
    ],
    2,
    'Whenever a player would receive priority, the game checks state-based actions. A creature with damage ≥ toughness is destroyed.',
  ),
  q(
    'legend-rule',
    'You control Karn, the Great Creator and cast a second Karn from your hand. What happens?',
    [
      "You choose one Karn to keep; the other goes to its owner's graveyard",
      'Both Karns stay because they have different art',
      'The new Karn enters as a copy with no abilities',
      'You must sacrifice both Karns',
    ],
    0,
    "The legend rule is a state-based action: if you control two or more legendary permanents with the same name, you choose one to keep and put the rest into their owners' graveyards.",
  ),
  q(
    'commander-tax',
    'Your commander has already been cast once from the command zone this game. How much additional mana do you pay to cast it again?',
    ['{2} additional', '{4} additional', 'No additional cost', '{2} total replacement cost'],
    0,
    'Commander tax is {2} for each time you have previously cast your commander from the command zone this game. One prior cast means +{2}.',
  ),
  q(
    'first-strike',
    'Your 3/3 with first strike blocks their 3/3 without first strike. How much combat damage does each creature deal?',
    [
      'Both deal 3 to each other simultaneously',
      'Yours deals 3 first; theirs deals none if it dies',
      'Neither deals damage because they cancel out',
      "Theirs deals 3 first because it's attacking",
    ],
    1,
    "First strike creatures deal combat damage in the first combat damage step. If the blocker dies there, the attacker won't deal damage in the normal step.",
  ),
  q(
    'hexproof-target',
    'Your opponent controls a creature with hexproof. Can you target it with your Murder?',
    [
      'Yes, hexproof only stops opponents\' spells',
      'No, hexproof prevents targeting by opponents',
      'Yes, if you control Murder you can ignore hexproof',
      'Only if they attack you',
    ],
    1,
    'Hexproof means "This permanent can\'t be the target of spells or abilities your opponents control." Murder cannot target it.',
  ),
  q(
    'etb-trigger',
    'You cast a creature with "When this creature enters, draw a card." When does that ability trigger?',
    [
      'When you announce the spell',
      'When it resolves and enters the battlefield',
      'At the beginning of your next upkeep',
      'Only if an opponent controls more creatures',
    ],
    1,
    '"When ~ enters the battlefield" triggers trigger when the permanent enters the battlefield, which happens when the spell resolves.',
  ),
  q(
    'priority-pass',
    'You cast a spell. Your opponent passes. You pass. What happens?',
    [
      'The spell returns to your hand',
      'You must cast another spell',
      'The top spell on the stack resolves',
      'Combat begins',
    ],
    2,
    'When all players pass in succession with something on the stack, the top object resolves. Then players receive priority again.',
  ),
  q(
    'land-drop',
    "It's your main phase. You haven't played a land yet. Can you play a land and then cast a sorcery?",
    [
      'No, only one action per turn',
      'Yes, lands are played at sorcery speed during your main phase',
      'Only if the sorcery costs zero',
      'You must cast the sorcery first',
    ],
    1,
    'You may play one land during your turn when you have priority and the stack is empty, during your main phase. Sorceries have the same timing.',
  ),
  q(
    'indestructible-lethal',
    'A 3/3 indestructible creature is dealt 3 damage. Is it destroyed?',
    [
      'Yes, lethal damage destroys anything',
      'No, indestructible prevents destruction from damage',
      'Yes, but it returns to the battlefield',
      'It is exiled instead',
    ],
    1,
    "Indestructible means the permanent can't be destroyed. Lethal damage is marked but state-based actions won't destroy it.",
  ),
  q(
    'double-strike',
    'Your 2/2 with double strike is unblocked. How much damage does the defending player take?',
    ['2', '4', '2 in two steps of 1 each', '0 until combat damage step ends'],
    1,
    'Double strike deals damage in both the first strike and regular combat damage steps — 2 + 2 = 4 total to the player.',
  ),
  q(
    'flash-timing',
    'Your opponent casts a creature during their main phase. Can you respond with a Counterspell?',
    [
      'No, only on your turn',
      'Yes, instants can be cast while a spell is on the stack',
      'Only if you have priority before they cast',
      'Only during combat',
    ],
    1,
    'After a spell is cast, all players get priority. Instants (and spells with flash) can be cast in response while the stack is not empty.',
  ),
  q(
    'commander-damage',
    "In Commander, you've taken 21 combat damage from the same opponent's commander over the game. What happens?",
    [
      'You lose the game',
      'Nothing unless it was all in one attack',
      'You lose only if they attack with commander again',
      'Commander damage resets each turn',
    ],
    0,
    'In Commander, if a player has been dealt 21 or more combat damage by a single commander over the course of the game, they lose.',
  ),
  q(
    'replacement-damage',
    'You control a creature with "If this would be dealt damage, prevent that damage." It is dealt 3 damage. How much is marked?',
    [
      '3 damage is still marked',
      '0 damage — it is prevented',
      '1 damage because prevention replaces part',
      'It depends on who dealt the damage',
    ],
    1,
    'Replacement effects change what happens. If all damage would be prevented, none is marked on the creature.',
  ),
  q(
    'trample-block',
    'A 5/5 with trample is blocked by a 2/2. How much damage can trample over to the defending player?',
    ['5', '3', '2', '0 — trample only works when unblocked'],
    1,
    'Trample lets excess combat damage go to the player or planeswalker being attacked. 5 damage minus 2 lethal to the blocker leaves 3 trampling over.',
  ),
  q(
    'morph-face-down',
    'You cast a creature face-down using morph. Can your opponent target it with "Destroy target face-down creature"?',
    [
      "No, face-down creatures are colorless and can't be targeted",
      'Yes, if it matches "face-down creature"',
      'Only after you turn it face up',
      'Face-down creatures are not creatures',
    ],
    1,
    'Face-down creatures are still creatures. They can be targeted by anything that legally targets a face-down creature.',
  ),
  q(
    'lifelink-damage',
    'Your 3/3 with lifelink deals 3 combat damage to a player. What happens?',
    [
      'You gain 3 life when the damage resolves',
      'You gain 3 life at end of turn',
      'Lifelink only works on spells',
      'The opponent loses 3 life instead',
    ],
    0,
    'Lifelink causes you to gain life equal to the damage dealt as that damage resolves.',
  ),
  q(
    'sacrifice-response',
    'Your opponent casts "Destroy target creature." In response, you sacrifice that creature. Does their spell still resolve?',
    [
      'No, it is countered automatically',
      'Yes, but it fizzles with no legal target on resolution',
      'Yes, and you must choose another creature',
      'The sacrifice is illegal in response',
    ],
    1,
    'On resolution, the spell checks its target. If the creature is gone and the spell says "target creature" with no remaining legal targets, it fizzles.',
  ),
  q(
    'tokens-persist',
    'You create a Treasure token on your turn. Nothing removes it. On your next turn, is it still on the battlefield?',
    [
      'No — all tokens vanish at end of turn',
      'Yes — tokens stay until they leave the battlefield or the game ends',
      'It goes to the graveyard at cleanup and stays there',
      'Only creature tokens can remain',
    ],
    1,
    'Tokens are permanents. They remain on the battlefield until an effect causes them to leave. They are not removed automatically at end of turn.',
  ),
  q(
    'token-dies-graveyard',
    'Your 2/2 creature token is destroyed. Which is true?',
    [
      'It stays in the graveyard like a normal creature card',
      'It goes to the graveyard briefly, then ceases to exist as a state-based action',
      'It is exiled face down',
      'It returns to the token supply',
    ],
    1,
    'Tokens that die go to the graveyard, then state-based actions remove them from the game. They cease to exist and cannot be retrieved later.',
  ),
  q(
    'ward-cost',
    'Your opponent casts a spell targeting your creature with ward {2}. What must they do?',
    [
      'Pay {2} extra or the spell is countered when it resolves',
      'Pay {2} when the permanent becomes the target or the spell/ability is countered',
      'Nothing, ward only affects abilities',
      'Discard a card',
    ],
    1,
    'Ward triggers when the permanent becomes the target of a spell or ability an opponent controls. They may pay the cost or that spell/ability is countered.',
  ),
  q(
    'planeswalker-damage',
    'You attack an opponent with two 2/2 creatures. They control a planeswalker with 4 loyalty. Can you assign all damage to the planeswalker?',
    [
      'No, at least one creature must hit the player',
      'Yes, you may have combat damage that would be dealt to the player dealt to the planeswalker instead',
      'Only if the planeswalker has defender',
      'Damage must be divided equally',
    ],
    1,
    'When attacking a player who controls a planeswalker, you may have combat damage that would be dealt to the player be dealt to the planeswalker instead.',
  ),
  q(
    'copy-spell',
    "You cast Clone copying a 2/2 creature named Grizzly Bears. What is Clone's power and toughness when it enters?",
    [
      '0/0 until it copies',
      '2/2 as Grizzly Bears',
      '1/1 as a generic copy',
      'It enters as a 2/2 creature token',
    ],
    1,
    'Clone enters as a copy of the chosen creature. It is a nontoken creature permanent with the copied characteristics (2/2 for Grizzly Bears).',
  ),
  q(
    'missed-trigger',
    'Your "At the beginning of your upkeep, draw a card" trigger is missed. In a casual game, what is the usual fix?',
    [
      'The trigger is lost forever',
      "Put it on the stack now if it's still the same phase and reasonable",
      'Your opponent draws instead',
      'You lose the game for missing a trigger',
    ],
    1,
    'For forgotten triggered abilities, if noticed quickly and no decisions made since, players often put it on the stack in casual play. Competitive rules use stricter remedies.',
  ),
  q(
    'deathtouch-trample',
    'A 1/1 with deathtouch and trample is blocked by a 5/5. How much damage tramples over to the defending player?',
    ['0', '1', '4', '5'],
    0,
    'The attacker only has 1 power. Assign 1 damage to the blocker (lethal thanks to deathtouch). No damage remains to trample over.',
  ),
  q(
    'shroud-vs-hexproof',
    'You control a creature with shroud. Can you equip your own Equipment to it?',
    [
      'Yes, shroud only stops opponents',
      'No, shroud prevents targeting by anyone including you',
      'Yes, but only during combat',
      'Only if the Equipment gives hexproof',
    ],
    1,
    'Shroud means the permanent cannot be the target of spells or abilities — including yours. Hexproof only protects from opponents.',
  ),
  q(
    'combat-after-blockers',
    'After blockers are declared, your opponent casts Destroy target creature on your blocker. When can damage be assigned?',
    [
      'Immediately, before the spell resolves',
      'After the spell resolves and state-based actions are checked',
      'Combat is cancelled',
      'Only at end of combat step',
    ],
    1,
    'Players can cast instants after blockers. If the blocker is destroyed before the damage step, the attacker may become unblocked or assign damage differently.',
  ),
  q(
    'core-mana-ability-response',
    'A spell is on the stack. Can you tap a land for mana in response?',
    [
      'No — lands cannot be tapped while the stack is not empty',
      'Yes — mana abilities do not use the stack',
      'Only on your turn',
      'Only if the spell is an instant',
    ],
    1,
    'Activated mana abilities can be used while spells are on the stack and do not use the stack themselves.',
  ),
  q(
    'core-replacement-prevent',
    'A 3/3 would take 3 damage, but an effect prevents that damage. How much damage is marked on the creature?',
    [
      '3 — prevention does not remove marked damage',
      '0 — prevented damage is never dealt or marked',
      '1 — minimum one damage is always marked',
      '3 until end of turn, then removed',
    ],
    1,
    'If damage is prevented, it is never dealt, so none is marked on the creature.',
  ),
  q(
    'core-flash-timing',
    'You have a creature card with flash in your hand. When can you cast it?',
    [
      'Only during your main phase',
      'Any time you could cast an instant',
      'Only during combat',
      'Only if you have no other creatures',
    ],
    1,
    'Flash allows you to cast the spell any time you could cast an instant.',
  ),
  q(
    'core-kicker-cost',
    'You cast a spell with kicker and pay the kicker cost in addition to its mana cost. What happens?',
    [
      'You create a copy of the spell',
      'You get the additional effect tied to kicker',
      'Kicker only works on sorceries',
      'The spell costs {0}',
    ],
    1,
    'Paying kicker is an additional cost when casting; if paid, the spell has the kicker effect when it resolves.',
  ),
  q(
    'core-ward-decline',
    'Your spell targets an opponent\'s creature with ward {2}. They choose not to pay. What happens?',
    [
      'The spell resolves anyway',
      'The spell is countered',
      'You must pay {2} instead',
      'The target changes to another creature',
    ],
    1,
    'When a permanent with ward becomes the target of a spell or ability, the spell or ability is countered unless ward is paid.',
  ),
  q(
    'core-cascade-must-cast',
    'Cascade exiles cards until it finds a nonland card with lesser mana value. Must you cast that card?',
    [
      'Yes — you must cast it',
      'No — you may cast it for free but are not forced to',
      'It goes to your hand instead',
      'Cascade only finds lands',
    ],
    1,
    'Cascade lets you cast the revealed card without paying its mana cost, but you may choose not to cast it.',
  ),
  q(
    'core-mana-value-x',
    'You cast Fireball with X=4. Its mana cost is {X}{R}. What is its mana value on the stack?',
    [
      '1',
      '4',
      '5',
      'X',
    ],
    2,
    'Mana value is the mana cost on the stack, including X. {X}{R} with X=4 gives a mana value of 5.',
  ),
  q(
    'core-etb-humility',
    'Humility is on the battlefield. A 5/5 creature with flying and trample attacks. What abilities does it have in combat?',
    [
      'Flying and trample only',
      'None — Humility removes all abilities and sets power and toughness to 1/1',
      'Only trample',
      'Flying only',
    ],
    1,
    'Humility removes all abilities from creatures and sets their power and toughness to 1/1.',
  ),
  q(
    'core-proliferate-poison',
    'You proliferate. An opponent has three poison counters. What happens?',
    [
      'Nothing — proliferate only affects permanents',
      'They get a fourth poison counter',
      'They lose the game immediately',
      'Poison counters are removed instead',
    ],
    1,
    'Proliferate lets you give each chosen player and/or permanent another counter of each kind they already have.',
  ),
  q(
    'core-split-second-cast',
    'An opponent casts a split second spell. Can you cast an instant in response?',
    [
      'Yes — split second only stops sorceries',
      'No — players cannot cast spells while a split second spell is on the stack',
      'Only counterspells',
      'Only if you have priority first',
    ],
    1,
    'While a split second spell is on the stack, players cannot cast spells (mana abilities are still allowed).',
  ),
]
