import { q, type TriviaQuestion } from './types'

/**
 * Hand-curated rules trivia. Answers checked against Comprehensive Rules /
 * official judge articles (2024–2026).
 */
export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  q(
    'stack-response-order',
    'You cast Lightning Bolt on a 5/5. Your opponent responds with Giant Growth (+3/+3). The stack resolves top-down. What happens?',
    [
      'Bolt fizzles because the creature changed',
      'Giant Growth resolves first; the creature becomes 5/8 and survives 3 damage',
      'Lightning Bolt resolves first; the 5/5 dies before the pump',
      'Both spells are countered',
    ],
    1,
    'The response is on top of the stack, so Giant Growth resolves first. Then Bolt deals 3 damage to a 5/8 creature.',
  ),
  q(
    'sba-lethal-damage',
    'A 2/2 has 2 damage marked on it and no one has passed priority. What happens?',
    [
      'Nothing until someone casts a spell',
      'The damage clears at end of turn',
      'State-based actions destroy it for lethal damage',
      'It stays on the battlefield until combat ends',
    ],
    2,
    'Before any player receives priority, the game checks state-based actions. A creature with damage ≥ toughness is put into its owner\'s graveyard.',
  ),
  q(
    'legend-rule',
    'You control Karn, the Great Creator and cast another Karn from your hand. What happens?',
    [
      'You choose one Karn to keep; the others go to their owners\' graveyards',
      'Both stay because they are different printings',
      'The new Karn enters as a nonlegendary copy',
      'You must sacrifice both',
    ],
    0,
    'The legend rule is a state-based action: if you control two or more legendary permanents with the same name, you choose all but one and put the rest into their owners\' graveyards.',
  ),
  q(
    'commander-tax-once',
    'You have cast your commander from the command zone once already this game. How much extra mana do you pay to cast it from the command zone again?',
    ['{1}', '{2}', '{4}', 'None'],
    1,
    'Commander tax is {2} for each previous time you cast that commander from the command zone this game. One prior cast means +{2}.',
  ),
  q(
    'commander-tax-hand',
    'Your commander is in your hand. You cast it from your hand (not the command zone). Does commander tax apply?',
    [
      'Yes — tax applies whenever you cast your commander',
      'No — tax only applies when casting from the command zone',
      'Yes — but only half the tax',
      'Only if it was in the command zone earlier this turn',
    ],
    1,
    'The additional {2} per prior cast applies only when casting from the command zone. Casting from hand uses its normal mana cost.',
  ),
  q(
    'first-strike-block',
    'Your 3/3 with first strike blocks their 3/3 without first strike. How much combat damage is dealt?',
    [
      'Both deal 3 to each other at the same time',
      'Yours deals 3 in the first step; theirs deals none if it dies',
      'Neither deals damage',
      'The attacker always deals damage first',
    ],
    1,
    'First strike creatures deal combat damage in the first combat damage step. If the blocker dies there, it won\'t deal damage in the normal step.',
  ),
  q(
    'double-strike',
    'A 2/2 with double strike and no first strike blocks a 3/3 with no abilities. How much total damage can the 2/2 assign to the 3/3 across combat damage steps?',
    [
      '2 — only in the first step',
      '4 — 2 in the first step and 2 in the second',
      '3 — split however the attacker chooses',
      '0 — double strike only helps when attacking',
    ],
    1,
    'Double strike lets a creature deal combat damage in both the first-strike step and the regular combat damage step.',
  ),
  q(
    'hexproof-opponent',
    'An opponent controls a creature with hexproof. Can you cast your Murder targeting it?',
    [
      'Yes — hexproof only stops combat damage',
      'No — hexproof stops opponents from targeting it',
      'Yes — if you controlled it earlier this turn',
      'Only during your main phase',
    ],
    1,
    'Hexproof means the permanent can\'t be the target of spells or abilities your opponents control.',
  ),
  q(
    'shroud-vs-hexproof',
    'A creature has shroud. Which is true?',
    [
      'Only opponents can\'t target it',
      'No player can target it',
      'It can still be targeted by its controller\'s auras',
      'Shroud and hexproof work the same way',
    ],
    1,
    'Shroud means no player can target that permanent. Hexproof only stops opponents.',
  ),
  q(
    'etb-trigger-timing',
    'You cast a creature with "When this creature enters, draw a card." When does that ability go on the stack?',
    [
      'When you announce the spell',
      'When the spell resolves and the creature is on the battlefield',
      'At the beginning of your next upkeep',
      'Only if an opponent controls more creatures',
    ],
    1,
    'Enter-the-battlefield abilities trigger when the permanent enters. The trigger is put on the stack after the creature is already on the battlefield.',
  ),
  q(
    'mana-abilities-stack',
    'Your opponent taps a Forest for {G} while casting a spell. Can you respond with an instant before they get the mana?',
    [
      'Yes — tapping uses the stack',
      'No — mana abilities do not use the stack',
      'Only if you have priority from a previous spell',
      'Yes — but only with Split Second instants',
    ],
    1,
    'Activated mana abilities resolve immediately and never go on the stack, so no one can respond to them.',
  ),
  q(
    'lands-play-stack',
    'During your main phase you play a land from your hand. Does that use the stack?',
    [
      'Yes — lands are spells',
      'No — playing a land is a special action that does not use the stack',
      'Yes — but only if an opponent controls an Island',
      'Only if the land has an enters ability',
    ],
    1,
    'Playing a land is a turn-based action, not a spell. Opponents cannot respond to you putting it onto the battlefield.',
  ),
  q(
    'trample-single-blocker',
    'Your 5/5 with trample is blocked by a 2/2. You must assign at least 2 damage to the blocker before trampling over. You assign exactly 2 to the blocker. How much hits the defending player?',
    [
      '0',
      '3',
      '5',
      '2',
    ],
    1,
    'After lethal damage is assigned to all blockers, remaining damage may be assigned to the defending player. 5 − 2 = 3 trample damage.',
  ),
  q(
    'trample-deathtouch-block',
    'Your 5/5 with trample and deathtouch is blocked by one 4/4 creature. How much damage must you assign to that blocker?',
    [
      '4 — equal to its toughness',
      '1 — that is lethal because of deathtouch',
      '5 — all damage must go to blockers first',
      '0 — deathtouch skips blockers',
    ],
    1,
    'For trample, you must assign lethal damage to each blocker. Any nonzero damage from a deathtouch source is lethal, so 1 damage is enough.',
  ),
  q(
    'deathtouch-indestructible',
    'A 1/1 with deathtouch blocks your 10/10 with no abilities. Your creature has indestructible. What happens in the first combat damage step (no first strike)?',
    [
      'Your 10/10 is destroyed by deathtouch',
      'Your 10/10 survives; indestructible ignores the destroy effect from deathtouch damage',
      'Both are destroyed',
      'Deathtouch does not work on creatures without trample',
    ],
    1,
    'Deathtouch marks lethal damage, but indestructible prevents destruction from damage and destroy effects.',
  ),
  q(
    'protection-red',
    'A creature has protection from red. An opponent casts Lightning Bolt (a red spell) targeting it. What happens?',
    [
      'The spell resolves and deals 3 damage',
      'The spell cannot legally target that creature',
      'It takes damage but cannot be destroyed',
      'Protection only stops red creatures',
    ],
    1,
    'Protection from red means it can\'t be targeted, blocked, damaged, or enchanted/equipped by red sources. Lightning Bolt cannot target it.',
  ),
  q(
    'ward-cost',
    'You cast a spell targeting an opponent\'s creature with ward {2}. What happens?',
    [
      'The spell is countered automatically',
      'The creature\'s controller may pay {2}; if they do, your spell is countered',
      'You must pay {2} or the spell fizzles',
      'Ward only works against creatures',
    ],
    1,
    'When a permanent with ward becomes the target of a spell or ability an opponent controls, its controller may pay the ward cost. If they do, that spell or ability is countered.',
  ),
  q(
    'fizzle-illegal-target',
    'You cast Murder targeting a creature. Before Murder resolves, your opponent gains hexproof on that creature. What happens to Murder?',
    [
      'It resolves and does nothing',
      'It is countered by the rules — all targets are illegal on resolution',
      'You choose a new target',
      'It waits until hexproof ends',
    ],
    1,
    'On resolution, if every target is illegal, the spell or ability is countered by the rules (it "fizzles").',
  ),
  q(
    'counterspell-timing',
    'You begin to cast a creature spell. When can an opponent cast Counterspell?',
    [
      'Only after it enters the battlefield',
      'While it is on the stack, before it resolves',
      'Only during your upkeep',
      'Never — creatures can\'t be countered',
    ],
    1,
    'Cast spells and abilities use the stack. Opponents can cast instants (like Counterspell) in response while your spell is still on the stack.',
  ),
  q(
    'split-second-response',
    'Your opponent casts a split second instant. Which can you still do before it resolves?',
    [
      'Cast any instant',
      'Activate mana abilities',
      'Cast a sorcery',
      'Activate equip abilities',
    ],
    1,
    'Split second stops players from casting spells or activating abilities that aren\'t mana abilities while it\'s on the stack. Mana abilities still work.',
  ),
  q(
    'priority-pass',
    'You cast a sorcery. It resolves. You want to cast another sorcery. What must happen first?',
    [
      'Nothing — you may cast it immediately',
      'Both players must pass priority with an empty stack',
      'Combat must happen',
      'Your opponent must draw a card',
    ],
    1,
    'Sorceries can only be cast during a main phase when the stack is empty and you have priority. After your first sorcery resolves, players must pass priority again.',
  ),
  q(
    'tokens-cease-to-exist',
    'A 1/1 token creature dies. Where does it go?',
    [
      'Its owner\'s graveyard',
      'Exile until end of turn',
      'It ceases to exist instead of going to a zone',
      'The command zone',
    ],
    2,
    'Tokens that would change zones to any place other than the battlefield cease to exist instead.',
  ),
  q(
    'clone-etb',
    'You cast a Clone entering as a copy of a 3/3 creature on the battlefield. What is Clone\'s power and toughness?',
    [
      '0/0 until something else happens',
      '3/3 — copy effects apply on the battlefield',
      '1/1 — Clone\'s printed stats',
      'It is not a creature',
    ],
    1,
    'Clone\'s ability is a replacement effect: it enters as a copy, so it has the same characteristics as what it copied.',
  ),
  q(
    'sacrifice-target',
    'Village Rites says "Sacrifice a creature. Draw two cards." When do you choose which creature?',
    [
      'When the spell resolves',
      'As you pay the cost while casting — before opponents can respond to the spell on the stack',
      'At random',
      'After you draw',
    ],
    1,
    'Sacrificing is part of paying costs to cast the spell. Costs are paid during the casting process, before the spell resolves.',
  ),
  q(
    'triggered-vs-activated',
    'Which uses the stack and can be responded to?',
    [
      'Tapping a land for mana',
      'A triggered ability that says "When ~ enters, draw a card"',
      'Playing a land',
      'Paying life for a Phyrexian mana symbol',
    ],
    1,
    'Triggered abilities (except mana abilities) go on the stack. Mana abilities and playing lands do not.',
  ),
  q(
    'lifelink-combat',
    'Your 3/3 with lifelink deals 3 combat damage to an opponent. How much life do you gain?',
    [
      '0 — lifelink only works on players',
      '3',
      '6',
      '1 per point of damage that would be dealt',
    ],
    1,
    'Lifelink causes you to gain life equal to the damage dealt by the source with lifelink. Three damage dealt means 3 life gained.',
  ),
  q(
    'deathtouch-trample-player',
    'Your 3/3 with deathtouch and trample is blocked by one 2/2. How much damage can be assigned to the defending player?',
    [
      '0 — all damage must kill the blocker',
      '1 — assign 1 lethal to the blocker, 2 tramples over',
      '3 — trample ignores blockers',
      '2 — you must assign full toughness to the blocker',
    ],
    1,
    'Assign 1 damage to the blocker (lethal with deathtouch). The remaining 2 damage tramples to the defending player.',
  ),
  q(
    'indestructible-destroy',
    'Your opponent casts Destroy Target Permanent on your Darksteel Colossus (indestructible). What happens?',
    [
      'It is destroyed',
      'The spell resolves but cannot destroy an indestructible permanent',
      'The spell cannot target it',
      'It becomes a 0/0',
    ],
    1,
    'Indestructible permanents ignore effects that say "destroy." The spell still resolves if it had other effects or legal targets.',
  ),
  q(
    'regenerate-obsolete',
    'An effect says "Regenerate target creature." A regenerated creature that would be destroyed this turn…',
    [
      'Is exiled instead',
      'Instead has all damage removed and is not destroyed (if regenerate resolved in time)',
      'Gains indestructible permanently',
      'Regenerate still works on any creature without reminder text',
    ],
    1,
    'Regenerate replaces destruction with removing damage, tapping, and removing the creature from combat. Few modern cards use it, but the rules still exist.',
  ),
  q(
    'planeswalker-loyalty-ability',
    'You activate a planeswalker\'s +1 loyalty ability. Does it use the stack?',
    [
      'No — loyalty abilities are mana abilities',
      'Yes — it is an activated ability on the stack',
      'Only if an opponent controls a creature',
      'Only the − abilities use the stack',
    ],
    1,
    'Loyalty abilities are activated abilities. They go on the stack and can be responded to like other activated abilities (they are not mana abilities).',
  ),
  q(
    'planeswalker-zero-loyalty',
    'A planeswalker on the battlefield has 0 loyalty. What happens before anyone gets priority?',
    [
      'It stays at 0',
      'State-based actions put it into its owner\'s graveyard',
      'Its controller loses the game',
      'It becomes a creature',
    ],
    1,
    'If a planeswalker has 0 loyalty, state-based actions put it into its owner\'s graveyard.',
  ),
  q(
    'combat-damage-simultaneous',
    'Two 3/3 creatures with no abilities block and attack each other (one blocks the other). When is combat damage dealt?',
    [
      'The attacker deals damage first',
      'Both deal damage at the same time in the combat damage step',
      'The defender chooses order',
      'Damage is dealt during the end step',
    ],
    1,
    'In the normal combat damage step, all assigned combat damage is dealt simultaneously (unless first strike / double strike applies).',
  ),
  q(
    'must-attack',
    'An effect says "This creature attacks each combat if able." It is tapped. Can its controller declare it as an attacker?',
    [
      'Yes — tapped creatures can still attack',
      'No — a tapped creature cannot be declared as an attacker',
      'Only if it has haste',
      'Only if it has vigilance',
    ],
    1,
    'Tapped creatures cannot be declared as attackers. If it cannot attack (because it is tapped), the "if able" clause is satisfied.',
  ),
  q(
    'vigilance-attack',
    'A creature with vigilance attacks. Is it tapped when attackers are declared?',
    [
      'Yes — attacking always taps',
      'No — vigilance lets it attack without tapping',
      'Only if it also has haste',
      'It taps in the damage step',
    ],
    1,
    'Vigilance means the creature does not tap as it attacks.',
  ),
  q(
    'haste-summoning-sickness',
    'You cast a creature with haste on your turn. Can it attack this turn?',
    [
      'No — all creatures have summoning sickness',
      'Yes — haste lets it attack and {T} the turn it enters',
      'Only if it was in your hand at start of turn',
      'Only if you control a Mountain',
    ],
    1,
    'Haste allows the creature to ignore summoning sickness for attacking and for using {T} abilities with the summoning-sickness restriction.',
  ),
  q(
    'summoning-sickness-ability',
    'You cast a creature without haste. Can you activate its "{T}: Draw a card" ability the turn it entered?',
    [
      'Yes — only attacking is restricted',
      'No — summoning sickness stops {T} abilities too',
      'Yes — if you pay {2}',
      'Only on your opponent\'s turn',
    ],
    1,
    'Summoning sickness prevents creatures from attacking and from activating abilities with {T} in the cost unless they have haste.',
  ),
  q(
    'flash-timing',
    'You have a creature with flash in your hand. When can you cast it?',
    [
      'Only during your main phase',
      'Any time you could cast an instant',
      'Only in response to a sorcery',
      'Only on your opponent\'s turn',
    ],
    1,
    'Flash allows you to cast the spell any time you could cast an instant.',
  ),
  q(
    'morph-face-down',
    'A face-down creature with morph is on the battlefield. What is its mana value for spells like Murderous Cut?',
    [
      'The mana value of the face-up side',
      '0',
      '1',
      'It cannot be targeted',
    ],
    1,
    'Face-down creatures have mana value 0. Their characteristics are those of a generic 2/2 creature with no name, types, or abilities.',
  ),
  q(
    'layer-timestamp',
    'One effect sets a creature\'s power to 1. A later effect gives it +3/+3. Both are continuous effects on the battlefield. Generally, which applies last in the power/toughness layer?',
    [
      'Always the +3/+3',
      'Always the power-setting effect',
      'Depends on timestamp order within the sublayer',
      'They cancel out',
    ],
    2,
    'Power/toughness changes from effects are applied in timestamp order within their sublayer (with special exceptions for * abilities).',
  ),
  q(
    'replacement-prevent-damage',
    'A source would deal 3 damage to you. You control a effect that says "If you would take damage, prevent 1 of that damage." How much do you take?',
    [
      '0',
      '1',
      '2',
      '3 — prevention does not stack automatically',
    ],
    2,
    'Replacement effects modify the event once. 3 damage becomes 2 damage after preventing 1.',
  ),
  q(
    'dies-trigger',
    'Your creature dies. You control "Whenever a creature dies, draw a card." When does that trigger?',
    [
      'Before the creature leaves the battlefield',
      'After it is in the graveyard — the die event happened',
      'Only at end of turn',
      'Only if you cast a spell that turn',
    ],
    1,
    'Leaves-the-battlefield and dies triggers see the permanent leave. The creature is in the graveyard when the ability triggers.',
  ),
  q(
    'bloodthirst-not-stack',
    'Which happens during the process of casting a spell, before it goes on the stack?',
    [
      'Resolving an enters-the-battlefield trigger',
      'Choosing modes, targets, and paying costs',
      'Dealing combat damage',
      'Putting triggered abilities on the stack',
    ],
    1,
    'Casting includes announcing the spell, choosing modes, targets, and how to pay costs. Only then is the spell put on the stack.',
  ),
  q(
    'x-spell-mana-value',
    'You cast Fireball and pay {X}{R} with X = 5. What is Fireball\'s mana value on the stack?',
    [
      '1',
      '5',
      '6',
      '0',
    ],
    2,
    'Mana value is the total mana in the mana cost, including X. For {X}{R} with X = 5, mana value is 6.',
  ),
  q(
    'partner-commander-tax',
    'You have partner commanders. You cast Partner A from the command zone twice. You have never cast Partner B from the command zone. How much tax applies when casting Partner B for the first time from the command zone?',
    [
      '{4} — taxes are shared',
      '{2} — only Partner A was cast twice',
      'None — first cast from the command zone',
      '{2} per partner combined',
    ],
    2,
    'Commander tax is tracked separately for each commander card. Partner B\'s first cast from the command zone has no tax.',
  ),
  q(
    'commander-damage-loss',
    'In Commander, you have taken 21 combat damage from a single commander over the course of the game. What happens?',
    [
      'Nothing unless your life total is 0',
      'You lose the game',
      'You cannot be attacked by that commander again',
      'That commander is exiled',
    ],
    1,
    'In Commander, 21 or more combat damage from a single commander causes you to lose the game (in addition to normal life loss rules).',
  ),
  q(
    'blocking-tapped',
    'Can you block with a tapped creature?',
    [
      'Yes — tapping does not matter for blocking',
      'No — only untapped creatures can block',
      'Only if it has reach',
      'Only on your turn',
    ],
    1,
    'Tapped creatures cannot be declared as blockers.',
  ),
  q(
    'reach-flying',
    'A 2/2 with reach blocks a 5/5 with flying. Is this legal?',
    [
      'No — flying creatures can only be blocked by creatures with flying',
      'Yes — reach allows blocking flying creatures',
      'Only if the reach creature also has flying',
      'Only during your turn',
    ],
    1,
    'Reach allows a creature to block creatures with flying as though it had flying for blocking purposes.',
  ),
  q(
    'menace-blocks',
    'A creature with menace is attacking. How many blockers must be declared to block it legally?',
    [
      'One',
      'Two or more',
      'Zero — menace is evasion like flying',
      'Any number, but they must be 4/4 or bigger',
    ],
    1,
    'Menace means "This creature can\'t be blocked except by two or more creatures."',
  ),
  q(
    'prowess-noncreature',
    'You control a creature with prowess and cast an instant. What happens?',
    [
      'Nothing — prowess only triggers on sorceries',
      'Prowess triggers and gives +1/+1 until end of turn',
      'It triggers twice',
      'Only if the instant targets the creature',
    ],
    1,
    'Prowess triggers whenever you cast a noncreature spell, including instants.',
  ),
  q(
    'cascade-exile',
    'You cast a spell with cascade. What happens to the cards you exile while looking for a cheaper spell?',
    [
      'They go to your graveyard',
      'They are exiled face up; you may cast the chosen one, then put the rest on the bottom in a random order',
      'They are destroyed',
      'They return to your hand',
    ],
    1,
    'Cascade exiles cards from your library until you find a legal cast. You may cast one, then put the rest on the bottom of your library in a random order.',
  ),
  q(
    'annihilator-trigger',
    'A creature with annihilator 1 attacks. When does the defending player sacrifice permanents relative to combat damage?',
    [
      'Before combat damage — during the declare attackers step, before blockers',
      'After all combat damage is dealt',
      'Only at end of turn',
      'Annihilator does not use the stack',
    ],
    0,
    'Annihilator triggers when attackers are declared. It goes on the stack and resolves before the declare blockers step — so sacrifices happen before combat damage.',
  ),
  q(
    'persist-counter',
    'A creature with persist and no -1/-1 counters on it dies. What happens if it returns with persist?',
    [
      'It returns with a +1/+1 counter',
      'It returns with a -1/-1 counter',
      'It returns indestructible',
      'Persist does nothing if it had no counters',
    ],
    1,
    'Persist returns the card with a -1/-1 counter on it (and at a smaller size for */* creatures per the card\'s rules text).',
  ),
  q(
    'undying-counter',
    'A 2/2 with undying dies with no +1/+1 counters on it. What happens?',
    [
      'It returns as a 2/2 with a -1/-1 counter',
      'It returns with a +1/+1 counter on it',
      'It stays dead',
      'Undying only works once per game total',
    ],
    1,
    'Undying returns the creature to the battlefield with a +1/+1 counter if it had no +1/+1 counters when it died.',
  ),
  q(
    'equipment-respond',
    'You activate an Equipment\'s equip ability targeting your creature. Can your opponent Destroy Target Artifact in response?',
    [
      'No — equip does not use the stack',
      'Yes — equip is an activated ability on the stack',
      'Only if the Equipment is already attached',
      'Only during combat',
    ],
    1,
    'Equip is an activated ability. It goes on the stack and can be responded to before it resolves.',
  ),
  q(
    'aura-target-hexproof-own',
    'You control a creature with hexproof. Can you cast your own Aura enchanting it targeting that creature?',
    [
      'No — hexproof stops all targeting',
      'Yes — hexproof only stops opponents',
      'Only if the Aura gives +1/+1',
      'Only on your opponent\'s turn',
    ],
    1,
    'Hexproof only restricts what your opponents can target. You may target your own hexproof permanents.',
  ),
  q(
    'fight-both-damage',
    'You cast Prey Upon — your 4/4 fights target creature they control (a 4/4). How is damage dealt?',
    [
      'Only your creature deals damage',
      'Each deals damage equal to its power to the other simultaneously',
      'The defending player chooses order',
      'Fight damage uses the stack',
    ],
    1,
    'Fight causes each chosen creature to deal damage equal to its power to the other. This happens as the spell or ability resolves, not as combat damage.',
  ),
  q(
    'scry-draw-replacement',
    'You control "If you would draw a card, scry 1 instead" and an effect would make you draw two cards. What happens?',
    [
      'You scry 1 once total',
      'The replacement applies separately — you scry 1 twice instead of drawing two cards',
      'You draw one and scry 1',
      'Drawing cannot be replaced',
    ],
    1,
    'Each draw event is replaced separately unless an effect says otherwise. Two draws become two scry 1 events.',
  ),
  q(
    'discard-timing',
    'Your opponent casts Thoughtseize. When do you discard?',
    [
      'Before they choose a card',
      'As Thoughtseize resolves — after they see your hand and choose a nonland card',
      'At end of turn',
      'Only if you have seven cards in hand',
    ],
    1,
    'Thoughtseize resolves: they look at your hand, choose a nonland card, and you discard it as part of resolution.',
  ),
  q(
    'static-glorious-anthem',
    'You control Glorious Anthem (+1/+1 to your creatures) and cast a 2/2. What is its power and toughness on the battlefield?',
    [
      '2/2 until end of turn',
      '3/3 — static effects apply continuously',
      '2/2 — Anthem triggers once',
      '1/1',
    ],
    1,
    'Continuous static effects apply as soon as the creature is on the battlefield. Your 2/2 is 3/3 immediately.',
  ),
  q(
    'blink-etb-twice',
    'Your creature is exiled until end of turn, then returns. How many times do "enters the battlefield" abilities trigger?',
    [
      'Zero — it was the same object',
      'Once — it left and re-entered as a new object',
      'Twice — exile and return each trigger',
      'Only if an opponent controls a planeswalker',
    ],
    1,
    'When it returns, it is a new object on the battlefield. It triggers ETB abilities once when it enters again.',
  ),
  q(
    'last-known-info',
    'A creature dies and is put in the graveyard. A spell asks for "last known information" of that creature on the battlefield. What does it use?',
    [
      'Its stats in the graveyard as a creature card',
      'Its characteristics immediately before it left the battlefield',
      'Its printed text only',
      'Zero power and toughness',
    ],
    1,
    'Last known information uses the object\'s characteristics just before it moved zones.',
  ),
  q(
    'damage-wont-lose-life',
    'An effect says "Damage can\'t be prevented" and you would prevent 3 damage to you. Another effect says "Prevent all damage that would be dealt to you this turn." What happens?',
    [
      'All damage is prevented — prevention wins',
      'The "can\'t be prevented" effect stops prevention — you take the damage',
      'Neither effect applies',
      'You choose which effect wins',
    ],
    1,
    'If damage can\'t be prevented, prevention effects cannot apply to that damage.',
  ),
  q(
    'storm-count',
    'You cast three spells before casting a spell with storm. When storm resolves, how many copies are created?',
    [
      'One — only the spell before it counts',
      'Three — one copy per spell cast before it this turn',
      'Zero — storm is obsolete',
      'Four including the original',
    ],
    1,
    'Storm copies the spell for each spell cast before it this turn. Three prior spells means three copies (plus the original spell).',
  ),
  q(
    'end-step-discard',
    'It is your end step. You have eight cards in hand and must discard. When do you discard down to seven?',
    [
      'During the cleanup step, after you would draw if applicable',
      'Before the end step begins',
      'Only if an opponent makes you',
      'You never discard in Commander',
    ],
    0,
    'Discard to maximum hand size happens during the cleanup step at the end of your turn (unless an effect changes timing).',
  ),
]
